Add -r flag

diff --git a/profile-validate b/profile-validate
--- a/profile-validate
+++ b/profile-validate
@@ -7,6 +7,7 @@ usage() {
     echo " -v             Print verbose information"
     echo " -m             Mail the maintainers of broken profiles"
     echo " -b branch      Select the pacman branch to test with"
+    echo " -r             Remove profiles that don't pass the test"
     echo " -h             Print this help message"
     echo ''
     echo ' profile-validate test the current iso-profiles to ensure that they work with manjaro-architect.'
@@ -22,7 +23,8 @@ bswitch=false
 pkgs_target=/tmp/package_list
 PROFILES="/tmp/profiles"
 branch=manjaro-architect
-while getopts ":g:b:vmh" opt; do
+filter=false
+while getopts ":g:b:vmrh" opt; do
   case $opt in
     g)
       echo "Using the git branch: $OPTARG" >&2
@@ -38,6 +40,9 @@ while getopts ":g:b:vmh" opt; do
     b)
       echo "Using the git branch: $OPTARG" >&2
       pbranch=$OPTARG
+      ;;
+    r)
+      filter=true
       ;;
     h)
       usage
@@ -72,11 +77,6 @@ fi
 filter_packages() {
         # Parse package list based on user input and remove parts that don't belong to pacman
         cat "$pkgs_src" > $pkgs_target
-        
-        # Remove any packages tagged with >openrc and remove >systemd tags
-        sed -i '/>openrc/d' $pkgs_target
-        sed -i 's/>systemd //g' $pkgs_target
-
         # Remove any packages tagged with >i686 and remove >x86_64 tags
         sed -i '/>i686/d' $pkgs_target
         sed -i '/>nonfree_i686/d' $pkgs_target
@@ -86,18 +86,8 @@ filter_packages() {
         sed -i 's/>multilib //g' $pkgs_target
         sed -i 's/>nonfree_multilib //g' $pkgs_target
 
-        if [[ -e /tmp/.minimal ]]; then
-            # Remove >extra tags
-            sed -i 's/>basic //g' $pkgs_target
-            sed -i '/>extra/d' $pkgs_target
-        else
-            # Remove >basic tags
-            sed -i 's/>extra //g' $pkgs_target
-            sed -i '/>basic/d' $pkgs_target
-        fi
-        # remove >manjaro flags and >sonar flags+pkgs until we support it properly
-        sed -i '/>sonar/d' $pkgs_target
-        sed -i 's/>manjaro //g' $pkgs_target
+        sed -i 's/>basic //g' $pkgs_target
+        sed -i '/>extra/d' $pkgs_target
 
         # Remove commented lines
         # remove everything except the first word of every lines
@@ -108,10 +98,6 @@ filter_packages() {
         sed -i '/KERNEL/d' $pkgs_target
         # Remove empty lines
         sed -i '/^\s*$/d' $pkgs_target
-
-        # Remove packages that have been dropped from repos
-        grep -f /tmp/.available_packages $pkgs_target > /tmp/.tmp
-        mv /tmp/.tmp $pkgs_target
 }
 
 test_profile() {
@@ -120,13 +106,17 @@ test_profile() {
     $verbose && echo "Testing profile $profile"
     comm -23 <(sort -u "$pkgs_target") <(grep -v -e ”\" -e "\/" -e "\:" -e "pkgname" /tmp/.available_packages | sort -u) > /tmp/fails-$profile
     if [[ "$(cat /tmp/fails-$profile | wc -l)" -gt 0 ]]; then
-        echo -e "Profile \e[31m$profile\e[0m did not pass the test."
-        echo -e "The offending packages are: 
-        \e[31m$(cat /tmp/fails-$profile)\e[0m
-"
-        echo "$profile" >> /tmp/failed_profiles
-        source $(echo $PROFILES/*/$profile/profile.conf)
-        $mail && sendmail
+        if $filter; then
+          rm -rf $(echo $PROFILES/*/$profile)
+        else
+          echo -e "Profile \e[31m$profile\e[0m did not pass the test."
+          echo -e "The offending packages are: 
+          \e[31m$(cat /tmp/fails-$profile)\e[0m
+  "
+          echo "$profile" >> /tmp/failed_profiles
+          source $(echo $PROFILES/*/$profile/profile.conf)
+          $mail && sendmail
+        fi
     else
         rm /tmp/fails-$profile
         $verbose && echo -e "Profile \e[36m$profile\e[0m passed the test
@@ -136,7 +126,12 @@ test_profile() {
 }
 
 loop_profiles() {
-    for profile in $(echo $PROFILES/{manjaro,community}/* | xargs -n1 | cut -f5 -d'/' | grep -vE "netinstall|architect"); do
+  if $filter; then
+    profile_list="$(echo $PROFILES/{manjaro,community}/* | tr " " "\n" | cut -f7 -d'/' | grep -vE "netinstall|architect")"
+  else
+    profile_list="$(echo $PROFILES/{manjaro,community}/* | tr " " "\n" | cut -f5 -d'/' | grep -vE "netinstall|architect")"
+  fi
+    for profile in $profile_list; do
         profile_to_test="$profile"
         test_profile
     done
@@ -165,14 +160,17 @@ setup_profiles() {
 }
 
 list_available_pgs() {
-    cat <(pacman -Ssq) <(pacman -Sgq) <(expac "%S" -Ss | xargs -n1) | sort | uniq > /tmp/.available_packages
+      cat <(pacman -Ssq) <(pacman -Sgq) <(expac "%S" -Ss | tr " " "\n") | sort | uniq > /tmp/.available_packages    
 }
 
 main() {
     list_available_pgs 
+    if $filter; then
+      PROFILES='/usr/share/manjaro-architect/profiles'
+    fi
     setup_profiles
     loop_profiles
-    if [[ "$(cat /tmp/failed_profiles | wc -l 2> /dev/null)" -gt 0 ]]; then
+    if ! $filter && [[ "$(cat /tmp/failed_profiles 2> /dev/null | wc -l 2> /dev/null)" -gt 0 ]]; then
     echo -e "
 --------------
 Following profiles failed the test:
@@ -183,7 +181,7 @@ $(cat /tmp/failed_profiles | sort | uniq)" | mail -s "Iso-profile broken" "manja
 rm /tmp/failed_profiles
 exit 1
 fi
-rm /tmp/failed_profiles
+[[ -e "/tmp/failed_profiles" ]] && rm /tmp/failed_profiles || true
 }
 
 if $bswitch ; then
@@ -191,5 +189,3 @@ if $bswitch ; then
 fi
 
 main 
-
-
